### ISSUE TITLE
Document the requirements of the game

### ISSUE THREAD

**Issue by melaasar** [kelaasar/lemonade-stand#1]
Go to the website: http://www.ae4rv.com/games/lemonade.htm

Play the game for sometime, then document the requirements in:
https://github.com/kelaasar/lemonade-stand/blob/master/Requirements.md

Do this on a branch whose name is: issue-1

Then once you are ready with changes, push the branch, then make a Pull Request and add melaasar as reviewer.

**Comment by kelaasar** [comment]
Resolved.
